version: "3"

services:

  app:
    image: node:16.11
    container_name: starter
    # command: npm run dev
    ports:
      - 8080:8080
      - 9229:9229
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    tty: true
